// client/src/pages/(pages)/account/login.jsx
import React from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from '@components/link';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@hooks/auth';
import { FormWrapper } from '@components/form-wrapper';
import { FormSubmit } from '@components/form-submit';
import { FormError } from '@components/form-error';
import { FormLabel, FormInput } from '@ariakit/react';

export const LoginPage = () => {
    const navigate = useNavigate();
    const { authRedirect, mutateAuth, setAuthRedirect } = useAuth();
    
    const handleFormResponse = response => {
        navigate(authRedirect ?? '/');
        mutateAuth(response);
        setAuthRedirect();
    };
    
    return (
        <main className="form-fullscreen">
            <Helmet>
                <title>Login</title>
            </Helmet>
            <h1>Login</h1>
            <FormWrapper
                action="/api/account/login"
                method="post"
                autoComplete="off"
                autoCorrect="off"
                spellCheck="false"
                onResponse={ handleFormResponse }
                defaultValues={{
                    username: '',
                    password: ''
                }}
            >
                <fieldset>
                    <div className="form-infield">
                        <FormLabel name="username">
                            Username
                        </FormLabel>
                        <FormInput
                            name="username"
                            type="text"
                            autoComplete="username"
                            required
                        />
                        <FormError name="username" />
                    </div>
                    <div className="form-infield">
                        <FormLabel name="password">
                            Password
                        </FormLabel>
                        <FormInput
                            name="password"
                            type="password"
                            autoComplete="current-password"
                            required
                        />
                        <FormError name="password" />
                    </div>
                </fieldset>
                <fieldset>
                    <FormSubmit className="button--filled button--primary">
                        Submit
                    </FormSubmit>
                </fieldset>
                <p>Don't have an account? <Link to="/account/sign-up" className="link--regular">Sign up with an invite code</Link>.</p>
            </FormWrapper>
        </main>
    );
};

export default LoginPage;

// src/pages/(pages)/account/login/+page.svelte
<script>
    import Form from '$components/primitives/Form.svelte';
    import FormInput from '$components/primitives/FormInput.svelte';
    import FormSubmit from '$components/primitives/FormSubmit.svelte';
    import Link from '$components/primitives/Link.svelte';
    import { authStore } from '$lib/stores.svelte';

    const handleFormResponse = response => {
        authStore.update(response);
        authStore.login();
    };
</script>

<svelte:head>
    <title>Login | is the metro accessible?</title>
</svelte:head>

<main class="form-fullscreen">
    <h1>Login</h1>
    <Form
        action="/api/account/login"
        method="POST"
        autocomplete="off"
        autocorrect="off"
        spellcheck="false"
        onResponse={ handleFormResponse }
    >
        <fieldset>
            <div class="form-infield">
                <FormInput
                    name="username"
                    type="text"
                    autocomplete="username"
                    required
                >
                    Username
                </FormInput>
            </div>
            <div class="form-infield">
                <FormInput
                    name="password"
                    type="password"
                    autocomplete="current-password"
                    minlength="10"
                    required
                >
                    Password
                </FormInput>
            </div>
        </fieldset>
        <fieldset>
            <FormSubmit />
        </fieldset>
        <p>Don't have an account? <Link href="/account/sign-up" class="link--regular">Sign up with an invite code</Link>.</p>
    </Form>
</main>
