// src/pages/(main)/stop/[stop]/+page.svelte
<script>
    import Review from '$components/Review.svelte';
    import ReviewDrawer from '$components/ReviewDrawer.svelte';
    import TagList from '$components/TagList.svelte';
    import CardClose from '$components/CardClose.svelte';
    import ContributeButton from '$components/ContributeButton.svelte';
    import Menu from '$components/primitives/Menu.svelte';
    import MenuItem from '$components/primitives/MenuItem.svelte';
    import Link from '$components/primitives/Link.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import i18n from '$lib/i18n-strings.json';
    import { perspectiveStore } from '$lib/stores.svelte';

    import '$assets/styles/components/stop-details.scss';

    const { data } = $props();

    const gsvURL = $derived(
        'https://www.google.com/maps/@?' +
            new URLSearchParams({
                api: 1,
                map_action: 'pano',
                viewpoint: [
                    data.coordinates.latitude,
                    data.coordinates.longitude
                ].join(',')
            })
    );
</script>

<main class="sidebar-card stop-details-card">
    <div class="card__header">
        <h1>{ data.name }</h1>
        <div class="card__actions">
            <Menu>
                <MenuItem
                    type="link"
                    href={ gsvURL }
                    target="_blank"
                    rel="noreferrer"
                    class="menu__item"
                >
                    Open in Google Street View
                    <Icon name="link" />
                </MenuItem>
            </Menu>
            <CardClose />
        </div>
    </div>
    <span class="subtitle">
        { i18n.stopSubheadings[data.agency.vehicle] }
    </span>
    <TagList
        state={ data.accessibility }
        tags={ data.tags }
        rounded={ true }
    />
    <p class="stop-accessibility-info">
        { data.description ?? i18n.accessibilityStates[data.accessibility].description }
    </p>
    {#if data.reviews}
        <div class="review-container">
            {#if data.reviews.length}
                <ReviewDrawer>
                    {#each data.reviews as review}
                        <Review review={ review } />
                    {/each}
                    <ContributeButton />
                </ReviewDrawer>
            {:else}
                <ContributeButton />
            {/if}
        </div>
    {/if}
    {#if perspectiveStore.perspective == "agency"}
        <span class="source-link">
            Source: <Link target="_blank" href={ data.agency.url } rel="noreferrer" class="link--minimal">{ data.agency.name }</Link>
        </span>
    {/if}
</main>

// client/src/pages/(main)/stop/[stop]/index.jsx
import React from 'react';
import { useParams } from 'react-router-dom';
import { MenuItem } from '@ariakit/react';
import { Menu } from '@components/menu';
import { useQuery } from '@hooks/query';
import { usePerspectiveStore } from '@hooks/store';
import { TagList } from '@components/tag-list';
import { Review } from '@components/review';
import { ReviewDrawer } from '@components/review-drawer';
import { CardClose } from '@components/card-close';
import { Link } from '@components/link';
import { Icon } from '@components/icon';
import i18n from '@assets/i18n-strings.json';

import '@assets/styles/components/stop-details.scss';

export const StopDetails = () => {
    const { stop } = useParams();

    const perspective = usePerspectiveStore(state => state.perspective);
    
    const { data: details } = useQuery({
        method: 'post',
        url: '/api/stop-details',
        data: {
            id: stop,
            perspective
        }
    });
    
    const gsvURL = 'https://www.google.com/maps/@?' +
        new URLSearchParams({
            api: 1,
            map_action: 'pano',
            viewpoint: [
                details.coordinates.latitude,
                details.coordinates.longitude
            ].join(',')
        });
        
    return (
        <main className="sidebar-card stop-details-card">
            <div className="card__header">
                <h1>{ details.name }</h1>
                <div className="card__actions">
                    <Menu>
                        <MenuItem render={
                            <Link
                                to={ gsvURL }
                                target="_blank"
                                rel="noreferrer"
                                className="menu__item"
                            >
                                Open in Google Street View
                                <Icon name="link" />
                            </Link>
                        } />
                    </Menu>
                    <CardClose />
                </div>
            </div>
            <span className="subtitle">
                { i18n.stopSubheadings[details.agency.vehicle] }
            </span>
            <TagList
                className="tag-list--rounded"
                state={ details.accessibility }
                tags={ details.tags }
            />
            <p className="stop-accessibility-info">
                { details.description ?? i18n.accessibilityStates[details.accessibility].description }
            </p>
            { details.reviews && (
                <div className="review-container">
                    <ReviewDrawer>
                        { details.reviews.map(review => (
                            <Review
                                review={ review }
                                key={ review.id }
                            />
                        )) }
                    </ReviewDrawer>
                </div>
            ) }
            { perspective == "agency" && (
                <span className="source-link">
                    Source: <Link target="_blank" href={ details.agency.url } rel="noreferrer" className="link--minimal">{ details.agency.name }</Link>
                </span>
            ) }
        </main>
    );
};

export default StopDetails;
