// client/src/pages/(main)/stop/[stop].jsx
import React, { useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { MenuItem, Disclosure, DisclosureContent, useDisclosureStore } from '@ariakit/react';
import { Menu } from '@components/menu';
import { useQuery } from '@hooks/query';
import { useAuth } from '@hooks/auth';
import { useMapStore } from '@hooks/store';
import { AccessibilityState } from '@components/accessibility-state';
import { Review } from '@components/review';
import { Icon } from '@components/icon';
import i18n from '@assets/i18n-strings.json';

export const StopDetails = () => {
    const { stop } = useParams();
    
    const { data: details } = useQuery({
        method: 'post',
        url: '/api/stop-details',
        data: { id: stop }
    });
    
    const disclosureStore = useDisclosureStore();
    const disclosureState = disclosureStore.useState();
    const { auth, setAuthRedirect } = useAuth();
    const navigate = useNavigate();
    
    const flyTo = useMapStore(state => state.flyTo);
    
    useEffect(() => {
        if (!details?.coordinates) { return; }
        
        flyTo([
            details.coordinates.longitude,
            details.coordinates.latitude
        ]);
    }, [ details?.coordinates, flyTo ]);
    
    if (!details?.name) { return null; }
    
    const gsvURL = 'https://www.google.com/maps/@?' +
        new URLSearchParams({
            api: 1,
            map_action: 'pano',
            viewpoint: [
                details.coordinates.latitude,
                details.coordinates.longitude
            ].join(',')
        });
        
    const switchToReviewForm = () => {
        if (Object.keys(auth).length) {
            navigate('/review/' + stop);
        } else {
            navigate('/account/login');
            setAuthRedirect('/review/' + stop);
        }
    };
    
    const closeCard = () => navigate('/');
    
    const ContributeButton = () => (
        <button
            className="review-contribute"
            onClick={ switchToReviewForm }
        >
            <Icon name="add" />
            Contribute a review
        </button>
    );
    
    return (
        <main className="sidebar-card stop-details-card">
            <div className="card-header">
                <h1>{ details.name }</h1>
                <div className="card-actions">
                    <Menu>
                        <MenuItem render={
                            <a
                                href={ gsvURL }
                                target="_blank"
                                rel="noreferrer"
                                className="menu-item"
                            >
                                Open in Google Street View
                                <Icon name="link" />
                            </a>
                        } />
                    </Menu>
                    <button
                        className="button-rounded card-close"
                        aria-label="Close"
                        onClick={ closeCard }
                    >
                        <Icon name="close" />
                    </button>
                </div>
            </div>
            <span className="subtitle">
                { i18n.stopSubheadings[details.agency.vehicle] }
            </span>
            <ul className="stop-tags-container">
                <li>
                    <AccessibilityState
                        className="stop-accessibility-state"
                        state={ details.accessibility }
                        showHeading="group"
                    />
                </li>
                { details.tags.map(tag => (
                    <li className="stop-tag" key={ tag }>
                        <Icon name={ tag } />
                        { i18n.tagLabels[tag] }
                    </li>
                )) }
            </ul>
            <p className="stop-accessibility-info">
                { details.alert?.description ?? details.description ??
                    i18n.accessibilityStates[details.accessibility].description }
            </p>
            { details.reviews && (
                <div className="review-container">
                    { details.reviews.length > 0 ? (
                        <>
                            <Disclosure
                                className="review-drawer-toggle"
                                store={ disclosureStore }
                            >
                                { i18n.reviewsToggleStates[disclosureState.open ? 'hide' : 'show'] }
                                <Icon name="chevron" />
                            </Disclosure>
                            <DisclosureContent store={ disclosureStore }>
                                { details.reviews.map(review => (
                                    <Review
                                        review={ review }
                                        key={ review.id }
                                        showOptions={ false }
                                    />
                                )) }
                                <ContributeButton />
                            </DisclosureContent>
                        </>
                    ) : (
                        <ContributeButton />
                    ) }
                </div>
            ) }
            { details.alert && (
                <a
                    className="stop-alert-link link-external"
                    href={ details.alert.url }
                    target="_blank"
                >
                    View service alert details
                    <Icon name="link" />
                </a>
            ) }
            { (!details.alert && !details.reviews) && (
                <span className="source-link">
                    Source: <a target="_blank" href={ details.agency.url } rel="noreferrer" className="link-minimal">{ details.agency.name }</a>
                </span>
            ) }
        </main>
    );
};

export default StopDetails;

// src/pages/(main)/stop/[stop]/+page.svelte
<script>
    import Review from '$components/Review.svelte';
    import ReviewDrawer from '$components/ReviewDrawer.svelte';
    import TagList from '$components/TagList.svelte';
    import CardClose from '$components/CardClose.svelte';
    import ContributeButton from '$components/ContributeButton.svelte';
    import Menu from '$components/primitives/Menu.svelte';
    import MenuItem from '$components/primitives/MenuItem.svelte';
    import Link from '$components/primitives/Link.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import i18n from '$lib/i18n-strings.json';
    import { perspectiveStore } from '$lib/stores.svelte';

    import '$assets/styles/components/stop-details.scss';

    const { data } = $props();

    const gsvURL = $derived(
        'https://www.google.com/maps/@?' +
            new URLSearchParams({
                api: 1,
                map_action: 'pano',
                viewpoint: [
                    data.coordinates.latitude,
                    data.coordinates.longitude
                ].join(',')
            })
    );
</script>

<main class="sidebar-card stop-details-card">
    <div class="card__header">
        <h1>{ data.name }</h1>
        <div class="card__actions">
            <Menu>
                <MenuItem
                    type="link"
                    href={ gsvURL }
                    target="_blank"
                    rel="noreferrer"
                    class="menu__item"
                >
                    Open in Google Street View
                    <Icon name="link" />
                </MenuItem>
            </Menu>
            <CardClose />
        </div>
    </div>
    <span class="subtitle">
        { i18n.stopSubheadings[data.agency.vehicle] }
    </span>
    <TagList
        state={ data.accessibility }
        tags={ data.tags }
        rounded={ true }
    />
    <p class="stop-accessibility-info">
        { data.description ?? i18n.accessibilityStates[data.accessibility].description }
    </p>
    {#if data.reviews}
        <div class="review-container">
            {#if data.reviews.length}
                <ReviewDrawer>
                    {#each data.reviews as review}
                        <Review review={ review } />
                    {/each}
                    <ContributeButton />
                </ReviewDrawer>
            {:else}
                <ContributeButton />
            {/if}
        </div>
    {/if}
    {#if perspectiveStore.perspective == "agency"}
        <span class="source-link">
            Source: <Link target="_blank" href={ data.agency.url } rel="noreferrer" class="link--minimal">{ data.agency.name }</Link>
        </span>
    {/if}
</main>
