// client/src/pages/(pages)/review/[review].jsx
import React, { useState } from "react";
import { Helmet } from "react-helmet";
import { useParams } from "react-router-dom";
import { useQuery } from "@hooks/query";
import { AuthorLink } from "@components/author-link";
import { ReviewActions } from "@components/review-actions";
import { FormWrapper } from "@components/form-wrapper";
import { AttachmentViewer } from "@components/attachment-viewer";
import { AccessibilityState } from "@components/accessibility-state";
import { AccessibilitySelect } from "@components/accessibility-select";
import { CommentsInput } from "@components/comments-input";
import { TagList } from "@components/tag-list";
import { FormInput } from "@ariakit/react";
import { FormSubmit } from "@components/form-submit";
import { Button } from "@components/button";
import { Icon } from "@components/icon";
import { statePrioritySort } from '@common/utils';

import "@assets/styles/components/review-details.scss";

export const ReviewDetails = () => {
    const { review } = useParams();

    const [ editing, setEditing ] = useState(false);
    const [ deleted, setDeleted ] = useState(false);

    const { data: details, mutate } = useQuery({
        method: 'post',
        url: '/api/review-details',
        data: { id: review }
    });

    const timestampFormatted = new Intl.DateTimeFormat(false, {
        dateStyle: 'full', timeStyle: 'short'
    }).format(new Date(details.timestamp));

    const handleDelete = () => {
        setDeleted(true);
        setEditing(false);
    };

    const handleArchive = () => {
        mutate({ ...details, archived: !details.archived });
    };

    const handleEdit = (response, data) => {
        const newDetails = Object.fromEntries(
            Array.from(data.keys())
            .map(key => [
                key, key === 'accessibility[]' ? 
                    data.getAll(key) : data.get(key)
            ]
        ));

        newDetails.accessibility = newDetails['accessibility[]'];
        delete newDetails['accessibility[]'];

        newDetails.accessibility?.sort(statePrioritySort);
        newDetails.accessibility ??= [ 'unknown' ];
        
        setEditing(false);
        mutate({ ...details, ...newDetails });
    };

    let defaultValues = structuredClone(details);
    delete defaultValues.id;

    const fallbackValue = (
        <p className="review-details__fallback">None provided.</p>
    );

    return (
        <main className="page-fullscreen">
            <Helmet>
                <title>{ details.stop.name }</title>
            </Helmet>
            <FormWrapper
                className="review-details"
                action="/api/edit-review"
                method="post"
                autoComplete="off"
                defaultValues={ defaultValues }
                onResponse={ handleEdit }
            >
                <div className="review-details__header">
                    <h1>
                        { deleted ? (
                            <del>{ details.stop.name }</del>
                        ) : (
                            details.stop.name
                        ) }
                    </h1>
                    { !deleted && (
                        <ReviewActions
                            review={ details }
                            onEdit={ () => setEditing(true) }
                            onDelete={ handleDelete }
                            onArchive={ handleArchive }
                        />
                    ) }
                </div>
                <div className="review-details__author">
                    <span className="subtitle">Review by </span>
                    <AuthorLink author={ details.author } />
                </div>
                <div className="review-details__field">
                    <h2>Timestamp</h2>
                    <p className="review-details__timestamp">
                        <time dateTime={ details.timestamp }>
                            { timestampFormatted }
                        </time>
                        { details.archived && (
                            <Icon name="archived" title="Archived review" />
                        ) }
                    </p>
                </div>
                <div className="review-details__field">
                    <h2>Accessibility state</h2>
                    { editing ? (
                        <AccessibilitySelect />
                    ) : details.accessibility.map(accessibility => (
                        <AccessibilityState
                            className="accessibility-state"
                            state={ accessibility }
                            key={ accessibility }
                        />
                    )) }
                </div>
                <div className="review-details__field">
                    <h2>Feature tags</h2>
                    { details.tags?.length ? (
                        <TagList tags={ details.tags } />
                    ) : (
                        fallbackValue
                    ) }
                </div>
                <div className="review-details__field">
                    <h2>Comments</h2>
                    { editing ? (
                        <CommentsInput />
                    ) : details.comments ? (
                        <p>{ details.comments }</p>
                    ) : (
                        fallbackValue
                    ) }
                </div>
                <div className="review-details__field">
                    <h2>Attachments</h2>
                    { details.attachments?.length ? (
                        <AttachmentViewer attachments={ details.attachments } />
                    ) : (
                        fallbackValue
                    ) }
                </div>
                { editing && (
                    <FormInput type="hidden" name="id" value={ review } />
                ) }
                { editing && (
                    <div className="button-set">
                        <FormSubmit className="button--filled button--primary" />
                        <Button
                            className="button--filled"
                            type="button"
                            onClick={ () => setEditing(false) }
                        >
                            Cancel
                        </Button>
                    </div>
                ) }
            </FormWrapper>
        </main>
    );
};

export default ReviewDetails;

// src/pages/(pages)/review/[review]/+page.svelte
<script>
    import Form from "$components/primitives/Form.svelte";
    import Button from "$components/primitives/Button.svelte";
    import Icon from "$components/primitives/Icon.svelte";
    import AuthorLink from "$components/AuthorLink.svelte";
    import FormInput from "$components/primitives/FormInput.svelte";
    import FormSubmit from "$components/primitives/FormSubmit.svelte";
    import ReviewActions from "$components/ReviewActions.svelte";
    import AttachmentViewer from "$components/AttachmentViewer.svelte";
    import AccessibilityState from "$components/AccessibilityState.svelte";
    import AccessibilitySelect from "$components/AccessibilitySelect.svelte";
    import CommentsInput from "$components/CommentsInput.svelte";
    import TagList from "$components/TagList.svelte";
    import { invalidate } from '$app/navigation';
    import { page } from '$app/stores';

    import "$assets/styles/components/review-details.scss";

    const { data } = $props();

    let deleted = $state(false);
    let editing = $state(false);

    const timestampFormatted = new Intl.DateTimeFormat(false, {
        dateStyle: 'full', timeStyle: 'short'
    }).format(new Date(data.timestamp));

    const invalidatePage = () => invalidate('/api/review-details');
</script>

<svelte:head>
    <title>{ data.stop.name }</title>
</svelte:head>

{#snippet fallbackValue()}
    <p class="review-details__fallback">
        None provided.
    </p>
{/snippet}

<main class="page-fullscreen">
    <Form
        class="review-details"
        action="/api/edit-review"
        method="POST"
        autocomplete="off"
        onResponse={ invalidatePage }
        onSubmit={ () => editing = false }
    >
        <div class="review-details__header">
            <h1>
                {#if deleted}
                    <del>{ data.stop.name }</del>
                {:else}
                    { data.stop.name }
                {/if}
            </h1>
            {#if !deleted}
                <ReviewActions
                    review={ data }
                    onEdit={ () => editing = true }
                    onDelete={ () => { editing = false; deleted = true; } }
                    onArchive={ invalidatePage }
                />
            {/if}
        </div>
        <div class="review-details__author">
            <span class="subtitle">Review by </span>
            <AuthorLink author={ data.author } />
        </div>
        <div class="review-details__field">
            <h2>Timestamp</h2>
            <p class="review-details__timestamp">
                <time datetime={ data.timestamp }>
                    { timestampFormatted }
                </time>
                {#if data.archived}
                    <Icon name="archived" title="Archived review" />
                {/if}
            </p>
        </div>
        <div class="review-details__field">
            <h2>Accessibility state</h2>
            {#if editing}
                <AccessibilitySelect />
            {:else}
                {#each data.accessibility as accessibility}
                    <AccessibilityState
                        class="accessibility-state"
                        state={ accessibility }
                    />
                {/each}
            {/if}
        </div>
        <div class="review-details__field">
            <h2>Feature tags</h2>
            {#if data.tags?.length}
                <TagList tags={ data.tags } />
            {:else}
                {@render fallbackValue()}
            {/if}
        </div>
        <div class="review-details__field">
            <h2>Comments</h2>
            {#if editing}
                <CommentsInput />
            {:else if data.comments}
                <p>{ data.comments }</p>
            {:else}
                {@render fallbackValue()}
            {/if}
        </div>
        <div class="review-details__field">
            <h2>Attachments</h2>
            {#if data.attachments?.length}
                <AttachmentViewer attachments={ data.attachments } />
            {:else}
                {@render fallbackValue()}
            {/if}
        </div>
        {#if editing}
            <FormInput
                type="hidden"
                name="id"
                value={ $page.params.review }
            />
        {/if}
        {#if editing}
            <div class="button-set">
                <FormSubmit class="button--filled button--primary" />
                <Button
                    class="button--filled"
                    type="button"
                    onclick={ () => editing = false }
                >
                    Cancel
                </Button>
            </div>
        {/if}
    </Form>
</main>
