// client/src/pages/(main)/route/[route].jsx
import React from 'react';
import { Helmet } from 'react-helmet';
import { Link } from '@components/link';
import { useParams } from 'react-router-dom';
import { Tab, TabList, TabPanel, useTabStore } from '@ariakit/react';
import { CardClose } from '@components/card-close';
import { useQuery } from '@hooks/query';
import { AccessibilityState } from '@components/accessibility-state';
import { RouteIcon } from '@components/route-icon';
import i18n from '@assets/i18n-strings.json';

import '@assets/styles/components/route-details.scss';

export const RouteDetails = () => {
    const { route } = useParams();
    
    const tabStore = useTabStore();
    
    const { data: details } = useQuery({
        method: 'post',
        url: '/api/route-details',
        data: { id: route }
    });
    
    const renderBranch = branch => branch.stops.map(({ stop }, index) => (
        <li key={ stop.id + "-" + index }>
            <AccessibilityState
                className="stop-icon"
                state={ stop.accessibility }
                showHeading={ false }
                showIcon="alt"
            />
            <Link to={ "/stop/" + stop.id } className="link--minimal">{ stop.name }</Link>
        </li>
    ));
    
    return (
        <main className="sidebar-card route-details-card">
            <Helmet>
                <title>{ details.name }</title>
            </Helmet>
            <div className="card__header">
                <h1>{ details.name }</h1>
                <RouteIcon
                    number={ details.number }
                    color={ details.color }
                />
                <div className="card__actions">
                    <CardClose />
                </div>
            </div>
            <span className="subtitle">
                { i18n.routeSubheadings[details.agency.vehicle] }
            </span>
            <TabList className="tab-group" store={ tabStore }>
                { details.directions.map((direction, directionIndex) => (
                    <Tab key={ directionIndex }>
                        { i18n.directionHeadings[direction.heading] }
                    </Tab>
                )) }
            </TabList>
            { details.directions.map((direction, directionIndex) => (
                <TabPanel store={ tabStore } key={ directionIndex }>
                    <ul className="stop-list-tree">
                        { direction.segments.map((segment, segmentIndex) => {
                            return (segment.branches.length > 1) ? (
                                <div className="branch-set" key={ segmentIndex }>
                                    { segment.branches.map((branch, branchIndex) => (
                                        <div className={ branchIndex == 0 ? "branch-base" : "branch-deviation" } key={ branchIndex }>
                                            { renderBranch(branch) }
                                        </div>
                                    )) }
                                </div>
                            ) : (
                                renderBranch(segment.branches[0])
                            );
                        }) }
                    </ul>
                </TabPanel>
            )) }
        </main>
    );
};

export default RouteDetails;

// src/pages/(main)/route/[route]/+page.svelte
<script>
    import TabList from '$components/primitives/TabList.svelte';
    import TabItem from '$components/primitives/TabItem.svelte';
    import TabPanel from '$components/primitives/TabPanel.svelte';
    import Link from '$components/primitives/Link.svelte';
    import AccessibilityState from '$components/AccessibilityState.svelte';
    import RouteIcon from '$components/RouteIcon.svelte';
    import CardClose from '$components/CardClose.svelte';
    import i18n from '$lib/i18n-strings.json';
    import { page } from '$app/stores';
    import { mapStore } from '$lib/stores.svelte';

    import '$assets/styles/components/route-details.scss';

    const { data } = $props();

    $effect(() => {
        const stopIds = data.directions
            .map(direction => direction.segments).flat()
            .map(segment => segment.branches).flat()
            .map(branch => branch.stops).flat()
            .map(relation => relation.stop.id);

        mapStore.stopVisibility = stopIds;
        mapStore.routeVisibility = [ $page.params.route ];

        return () => {
            mapStore.stopVisibility = [];
            mapStore.routeVisibility = [];
        };
    });
</script>

<svelte:head>
    <title>{ data.name } | is the metro accessible?</title>
</svelte:head>

<main class="sidebar-card route-details-card">
    <div class="card__header">
        <h1>{ data.name }</h1>
        <RouteIcon
            number={ data.number }
            color={ data.color }
        />
        <div class="card__actions">
            <CardClose />
        </div>
    </div>
    <span class="subtitle">
        { i18n.routeSubheadings[data.agency.vehicle] }
    </span>
    <TabList defaultValue={ data.directions[0].heading }>
        {#snippet tabs()}
            {#each data.directions as direction}
                <TabItem id={ direction.heading }>
                    { i18n.directionHeadings[direction.heading] }
                </TabItem>
            {/each}
        {/snippet}
        {#each data.directions as direction}
            <TabPanel id={ direction.heading }>
                <ul class="stop-list-tree">
                    {#each direction.segments as segment}
                        {#if segment.branches.length > 1}
                            <div class="branch-set">
                                {#each segment.branches as branchValues, branchIndex}
                                    <div class={
                                        branchIndex == 0 ? "branch-base" : "branch-deviation"
                                    }>
                                        {@render branch(branchValues)}
                                    </div>
                                {/each}
                            </div>
                        {:else}
                            {@render branch(segment.branches[0])}
                        {/if}
                    {/each}
                </ul>
            </TabPanel>
        {/each}
    </TabList>
</main>

{#snippet branch({ stops })}
    {#each stops as { stop }}
        <li>
            <AccessibilityState
                class="stop-icon"
                state={ stop.accessibility }
                showHeading={ false }
                showIcon="alt"
            />
            <Link
                href={ "/stop/" + stop.id }
                class="link--minimal"
            >
                { stop.name }
            </Link>
        </li>
    {/each}
{/snippet}
