// client/src/components/attachment-input.jsx
import React, { useEffect } from 'react';
import { useDropzone } from 'react-dropzone';
import { AttachmentPopover } from '@components/attachment-popover';
import { Button } from '@components/button';
import { Icon } from '@components/icon';
import { useFormWrapperStore } from '@hooks/store';

import '@assets/styles/components/attachment-input.scss';

export const AttachmentInput = props => {
    const { name = "attachments" } = props;
    
    const [
        files,
        setFiles,
        clearFiles
    ] = useFormWrapperStore(state => [
        state.files,
        state.setFiles,
        state.clearFiles
    ]);
    
    const { getRootProps, getInputProps } = useDropzone({
        accept: {
            'image/jpeg': []
        },
        onDrop: acceptedFiles => {
            setFiles(name, acceptedFiles.map(file => Object.assign(file, {
                preview: URL.createObjectURL(file)
            })));
        }
    });
    
    const handleCleanup = file => URL.revokeObjectURL(file.preview);
    const handleDelete = file => setFiles(name, files[name].filter(comp => comp !== file));
    
    useEffect(() => {
        return () => {
            files[name]?.forEach(handleCleanup);
            clearFiles(name);
        };
    }, []);
    
    return (
        <ol className="attachment-input attachment-list">
            { files[name]?.map(file => (
                <li className="attachment" key={ file.preview }>
                    <img
                        src={ file.preview }
                        onLoad={ () => handleCleanup(file) }
                    />
                    <div className="attachment__actions">
                        <AttachmentPopover
                            name={ "attachmentsAlt[" + file.name + "]" }
                            isEditing={ true }
                        />
                        <Button
                            type="button"
                            className="button--overlay"
                            aria-label="Delete attachment"
                            onClick={ () => handleDelete(file) }
                        >
                            <Icon name="close" />
                        </Button>
                    </div>
                </li>
            )) }
            <li
                { ...getRootProps() }
                className="attachment-input__upload"
                role="button"
                aria-label="Choose files"
            >
                <input { ...getInputProps() } />
                <Icon name="upload" />
            </li>
        </ol>
    );
};

// src/components/AttachmentInput.svelte
<script>
    import FormInput from '$components/primitives/FormInput.svelte';
    import Popover from '$components/primitives/Popover.svelte';
    import Button from '$components/primitives/Button.svelte';
    import Icon from '$components/primitives/Icon.svelte';

    import '$assets/styles/components/attachment-input.scss';

    const { name = 'attachments' } = $props();

    let files = $state();
    let previews = $derived(Array.from(files ?? []).map(file => {
        return URL.createObjectURL(file);
    }));

    const handleCleanup = src => URL.revokeObjectURL(src);

    const handleDelete = index => {
        const updatedFiles = Array.from(files);
        updatedFiles.splice(index, 1);

        if (updatedFiles.length) {
            const dataTransfer = new DataTransfer();
            updatedFiles.forEach(file => {
                dataTransfer.items.add(file);
            });
            files = dataTransfer.files;
        } else {
            files = undefined;
        }
    };
</script>

<ol class="attachment-input attachment-list">
    {#each previews as preview, index}
        <li class="attachment">
            <img
                src={ preview }
                onload={ () => handleCleanup(preview) }
            />
            <div class="attachment__actions">
                <Popover
                    heading="Image description"
                    triggerLabel="+Alt"
                    triggerClass="button--overlay attachment__alt"
                    closeLabel="Done"
                    closeClass="button--filled button--primary"
                >
                    <FormInput
                        name={ "attachmentsAlt[" + files[index].name + "]" }
                        as="textarea"
                        placeholder="Describe the content of your image for other users"
                    />
                </Popover>
                <Button
                    class="button--overlay"
                    aria-label="Delete attachment"
                    onclick={ () => handleDelete(index) }
                >
                    <Icon name="close" />
                </Button>
            </div>
        </li>
    {/each}
    <li class="attachment-input__upload">
        <input
            bind:files={ files }
            type="file"
            accept="image/jpeg"
            { name }
            multiple
        />
        <Icon name="upload" />
    </li>
</ol>
