// client/src/components/big-radio.jsx
import React from 'react';
import { Radio } from '@ariakit/react';

import '@assets/styles/components/big-radio.scss';

export const BigRadio = props => {
    const { label, description, ...passthroughProps } = props;

    return (
        <label className="big-radio">
            <Radio { ...passthroughProps } />
            <div>
                <div className="big-radio__label">
                    { label }
                </div>
                <div className="big-radio__description">
                    { description }
                </div>
            </div>
        </label>
    );
};

export default BigRadio;

// src/components/BigRadio.svelte
<script>
    import '$assets/styles/components/big-radio.scss';

    const { label, description, ...passthroughProps } = $props();
</script>

<label class="big-radio">
    <input
        type="radio"
        { ...passthroughProps }
    />
    <div>
        <div class="big-radio__label">
            { label }
        </div>
        <div class="big-radio__description">
            { description }
        </div>
    </div>
</label>
