// client/src/components/card-close.jsx
import React from "react";
import { Button } from "@components/button";
import { Icon } from "@components/icon";
import { useNavigate } from "react-router-dom";

export const CardClose = () => {
    const navigate = useNavigate();

    const closeCard = () => navigate('/');

    return (
        <Button
            className="button--rounded"
            aria-label="Close"
            onClick={ closeCard }
        >
            <Icon name="close" />
        </Button>
    );
};

// src/components/CardClose.svelte
<script>
    import Button from '$components/primitives/Button.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import { goto } from '$app/navigation';

    const closeCard = () => goto('/');
</script>

<Button
    class="button--rounded"
    aria-label="Close"
    onclick={ closeCard }
>
    <Icon name="close" />
</Button>
