// client/src/components/review-drawer.jsx
import React from "react";
import { Disclosure, DisclosureContent, DisclosureProvider, useDisclosureStore } from '@ariakit/react';
import { ContributeButton } from '@components/contribute-button';
import { Icon } from '@components/icon';
import i18n from '@assets/i18n-strings.json';

import "@assets/styles/components/review-drawer.scss";

export const ReviewDrawer = props => {
    const { children } = props;

    const disclosureStore = useDisclosureStore();
    const disclosureState = disclosureStore.useState(state => state.open);

    if (!children?.length) {
        return <ContributeButton />;
    }

    return (
        <DisclosureProvider store={ disclosureStore }>
            <Disclosure className="review-drawer-toggle">
                { i18n.reviewsToggleStates[disclosureState ? 'hide' : 'show'] }
                <Icon
                    name={ disclosureState ? "chevron-up" : "chevron-down" }
                    className="icon--fixed-right"
                />
            </Disclosure>
            <DisclosureContent>
                { children }
                <ContributeButton />
            </DisclosureContent>
        </DisclosureProvider>
    );
};

// src/components/ReviewDrawer.svelte
<script>
    import { melt, createCollapsible } from '@melt-ui/svelte';
    import Button from '$components/primitives/Button.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import i18n from '$lib/i18n-strings.json';
    
    import '$assets/styles/components/review-drawer.scss';
    
    const { children } = $props();
    
    const {
        elements: { root, content, trigger },
        states: { open },
    } = createCollapsible();
</script>

<div use:melt={ $root }>
    <Button
        class="review-drawer-toggle"
        melt={ trigger }
    >
        { i18n.reviewsToggleStates[$open ? 'hide' : 'show'] }
        <Icon
            name={ $open ? "chevron-up" : "chevron-down" }
            class="icon--fixed-right"
        />
    </Button>
    <div use:melt={ $content }>
        {@render children()}
    </div>
</div>
