// src/pages/(pages)/profile/[username]/+page.svelte
<script>
    import Button from '$components/primitives/Button.svelte';
    import Review from '$components/Review.svelte';
    import { page } from '$app/stores';
    import { goto } from '$app/navigation';

    import '$assets/styles/components/profile.scss';

    const { data } = $props();

    const reviewCount = `${new Intl.NumberFormat().format(data.count)} review${data.count !== 1 ? 's' : ''}`;

    const currentPage = $derived(
        $page.url.searchParams.get('page') ?? 1
    );
    const moreReviewsAvailable = $derived(
        data.count > ((currentPage - 1) * 25 + data.reviews.length)
    );

    const incrementPage = () => {
        const searchParams = new URLSearchParams(
            $page.url.searchParams.toString()
        );
        searchParams.set('page', currentPage + 1);
        goto('?' + searchParams.toString());
    };
</script>

<svelte:head>
    <title>{ $page.params.username } | is the metro accessible?</title>
</svelte:head>

<main class="page-fullscreen">
    <div class="user-profile">
        <img
            class="profile-picture"
            src={ data.avatar }
            alt="Profile picture"
        />
        <h1>{ $page.params.username }</h1>
        <div class="subtitle">
            { reviewCount }
        </div>
        <div class="review-container">
            {#each data.reviews as review}
                <Review review={ review } />
            {/each}
        </div>
        {#if moreReviewsAvailable}
            <Button
                onclick={ incrementPage }
                class="button--filled button--primary"
            >
                Show more
            </Button>
        {/if}
    </div>
</main>

// client/src/pages/profile/[username].jsx
import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useInfiniteQuery } from '@hooks/query';
import { useAuth } from '@hooks/auth';
import { Review } from '@components/review';
import { Icon } from '@components/icon';

export const ProfilePage = props => {
    const { username } = useParams();
    
    const { data, size, setSize } = useInfiniteQuery(page => ({
        method: 'post',
        url: '/api/profile',
        data: { username, page: page + 1 }
    }));
    
    const details = data?.[data?.length - 1];
    const reviews = data?.map(page => page.reviews).flat();
    
    const { auth } = useAuth();
    
    const [ focusedIndex, setFocusedIndex ] = useState(-1);
    
    if (!details || !reviews) { return null; }
    
    const incrementPage = () => {
        setFocusedIndex(reviews.length);
        setSize(size + 1);
    };
    
    const reviewCount = `${new Intl.NumberFormat().format(details.count)} review${details.count > 1 ? 's' : ''}`;
    
    const moreReviewsAvailable = details.count > reviews.length;
    
    return (
        <div className="page-fullscreen">
            <Link
                className="button-rounded page-close"
                to="/"
                aria-label="Close"
            >
                <Icon name= "close" />
            </Link>
            <div className="user-profile">
                <img
                    className="profile-picture"
                    src={ details.avatar }
                    alt="Profile picture"
                />
                <h1>{ username }</h1>
                <div className="subtitle">
                    { reviewCount }
                </div>
                <div className="review-container">
                    { reviews.map((review, index) => (
                        <Review
                            ref={ index === focusedIndex ? i => i?.focus() : undefined }
                            review={ review }
                            key={ review.id }
                            showOptions={ (auth.username == username || auth.admin) }
                            allowEditing={ auth.admin }
                        />
                    )) }
                </div>
                { moreReviewsAvailable && (
                    <button
                        onClick={ incrementPage }
                        className="button-filled button-primary"
                    >
                        Show more
                    </button>
                ) }
            </div>
        </div>
    );
};

export default ProfilePage;
