// src/components/AttachmentViewer.svelte
<script>
    import BiggerPicture from 'bigger-picture';
    import Popover from '$components/primitives/Popover.svelte';
    import Button from '$components/primitives/Button.svelte';
    import { browser } from '$app/environment';

    import 'bigger-picture/css';
    import '$assets/styles/components/attachment-viewer.scss';

    const { attachments } = $props();

    const urlForSize = (filename, quality) =>
        "/api/attachment/" + quality + "/" + filename;

    let itemRefs = $state([]);
    const items = $derived(attachments.map((attachment, index) => {
        const large = attachment.sizes.find(size => size.quality == 'large');
        return {
            img: urlForSize(attachment.filename, 'large'),
            thumb: urlForSize(attachment.filename, 'small'),
            width: large.width,
            height: large.height,
            alt: attachment.alt,
            element: itemRefs[index]
        };
    }));

    const lightbox = browser && BiggerPicture({
        target: document.body
    });
</script>

<ol class="attachment-viewer attachment-list">
    {#each items as item, index}
        <li class="attachment">
            <Button
                class="attachment__enlarge"
                onclick={ () => lightbox.open({
                    items, position: index, scale: 0.9
                }) }
            >
                <img
                    src={ item.thumb }
                    alt={ item.alt }
                    bind:this={ itemRefs[index] }
                />
            </Button>
            {#if item.alt}
                <div class="attachment__actions">
                    <Popover
                        heading="Image description"
                        triggerLabel="Alt"
                        triggerClass="button--overlay attachment__alt"
                        closeLabel="Dismiss"
                    >
                        { item.alt }
                    </Popover>
                </div>
            {/if}
        </li>
    {/each}
</ol>

// client/src/components/attachment-viewer.jsx
import React from 'react';
import { Gallery, Item } from 'react-photoswipe-gallery';
import { AttachmentPopover } from '@components/attachment-popover';
import { Button } from '@components/button';

import 'photoswipe/dist/photoswipe.css'
import '@assets/styles/components/attachment-viewer.scss';

export const AttachmentViewer = props => {
    const { attachments } = props;
    
    if (!attachments?.length) { return; }
    
    const qualities = [ 'large', 'small' ];
    
    const images = attachments.map(attachment => {
        let sizes = {};
        qualities.forEach(quality => {
            sizes[quality] = attachment.sizes.find(size => size.quality === quality);
            sizes[quality].url = "/api/attachment/" + quality + "/" + attachment.filename;
        });
        
        return sizes;
    });
    
    return (
        <Gallery options={{
            mainClass: 'image-gallery',
            bgOpacity: 1,
            arrowPrev: false,
            arrowNext: false,
            padding: { top: 40, right: 15, bottom: 40, left: 15 },
            wheelToZoom: true
        }} >
            <ol className="attachment-viewer attachment-list">
                { images.map((image, index) => (
                    <Item
                        key={ index }
                        original={ image.large.url }
                        thumbnail={ image.small.url }
                        width={ image.large.width }
                        height={ image.large.height }
                    >
                        { props => (
                            <li className="attachment">
                                <Button
                                    onClick={ props.open }
                                    className="attachment__enlarge"
                                >
                                    <img
                                        ref={ props.ref }
                                        src={ image.small.url }
                                        alt={ attachments[index].alt }
                                    />
                                </Button>
                                <div className="attachment__actions">
                                    <AttachmentPopover
                                        alt={ attachments[index].alt }
                                    />
                                </div>
                            </li>
                        ) }
                    </Item>
                )) }
            </ol>
        </Gallery>
    );
};
