// src/components/AuthorLink.svelte
<script>
    import Link from '$components/primitives/Link.svelte';

    import "$assets/styles/components/author-link.scss";

    const { author } = $props();
</script>

<div class="author-link">
    <img
        class="profile-picture"
        src={ author.avatar }
        alt="Profile picture"
    />
    <Link
        href={ "/profile/" + author.username }
        class="link--minimal"
    >
        { author.username }
    </Link>
</div>

// client/src/components/author-link.jsx
import React from "react";
import { Link } from "@components/link";

import "@assets/styles/components/author-link.scss";

export const AuthorLink = props => {
    const { author } = props;

    return (
        <div className="author-link">
            <img className="profile-picture"
                src={ author.avatar }
                alt="Profile picture"
            />
            <Link
                to={ "/profile/" + author.username }
                className="review__author link--minimal"
            >
                { author.username }
            </Link>
        </div>
    );
};
