// src/components/ContributeButton.svelte
<script>
    import Button from '$components/primitives/Button.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import { page } from '$app/stores';
    import { goto } from '$app/navigation';

    const switchToReviewForm = () => {
        goto($page.url.pathname + '/review');
    };
</script>

<Button
    class="review-contribute"
    onclick={ switchToReviewForm }
>
    <Icon name="add" />
    Contribute a review
</Button>

// client/src/components/contribute-button.jsx
import React from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@hooks/auth";
import { Button } from "@components/button";
import { Icon } from "@components/icon";

export const ContributeButton = () => {
    const { auth, setAuthRedirect } = useAuth();
    const navigate = useNavigate();

    const switchToReviewForm = () => {
        if (Object.keys(auth).length) {
            navigate('./review');
        } else {
            navigate('/account/login');
            setAuthRedirect('./review');
        }
    };

    return (
        <Button
            className="review-contribute"
            onClick={ switchToReviewForm }
        >
            <Icon name="add" />
            Contribute a review
        </Button>
    );
};
