// src/components/primitives/FormSubmit.svelte
<script>
    import Button from '$components/primitives/Button.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import { getContext } from 'svelte';

    const { ...passthroughProps } = $props();

    const formStore = getContext('form');
</script>

<Button
    type="submit"
    class="button--filled button--primary"
    disabled={ formStore.isLoading }
    { ...formStore.isLoading && { 'aria-label': 'Loading...' } }
    { ...passthroughProps }
>
    {#if formStore.isLoading}
        <Icon name="spinner" />
    {:else}
        Submit
    {/if}
</Button>

// client/src/components/form-submit.jsx
import React, { forwardRef } from 'react';
import { useFormContext } from '@components/form-wrapper';
import { FormSubmit as FormSubmitChild } from '@ariakit/react';
import { Icon } from '@components/icon';

export const FormSubmit = forwardRef((props, ref) => {
    const { isLoading } = useFormContext();
    
    return (
        <FormSubmitChild
            ref={ ref }
            disabled={ isLoading }
            { ...isLoading && { 'aria-label': 'Loading...' } }
            { ...props }
        >
            { !isLoading ? "Submit" : <Icon name="spinner" /> }
        </FormSubmitChild>
    );
});
