// src/components/ReviewActions.svelte
<script>
    import Menu from '$components/primitives/Menu.svelte';
    import MenuItem from '$components/primitives/MenuItem.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import { authStore } from '$lib/stores.svelte';
    import { jsonFetch } from '$lib/fetch';

    const { review, onEdit, onDelete, onArchive } = $props();

    const isActionable = authStore.role == 'ADMIN' ||
        authStore.username == review.author.username;

    const handleDelete = async () => {
        await jsonFetch({
            url: '/api/delete-review',
            method: 'POST',
            body: { id: review.id }
        });
        onDelete();
    };

    const handleArchive = async () => {
        await jsonFetch({
            url: '/api/archive-review',
            method: 'POST',
            body: { id: review.id }
        });
        onArchive();
    };
</script>

{#if isActionable}
    <Menu>
        {#if authStore.role == 'ADMIN'}
            <MenuItem onclick={ onEdit }>
                <Icon name="pencil" />
                Edit
            </MenuItem>
        {/if}
        <MenuItem onclick={ handleArchive }>
            <Icon name="archive" />
            { !review.archived ?
                "Archive" : "Unarchive"
            }
        </MenuItem>
        <MenuItem onclick={ handleDelete }>
            <Icon name="trash" />
            Delete
        </MenuItem>
    </Menu>
{/if}

// client/src/components/review-actions.jsx
import React from "react";
import { Menu } from "@components/menu";
import { MenuItem } from "@ariakit/react";
import { Button } from "@components/button";
import { Icon } from "@components/icon";
import { useAuth } from "@hooks/auth";
import { useErrorStatus } from "@hooks/error";
import { queryHelper } from "@hooks/query";

export const ReviewActions = props => {
    const { review, onEdit, onDelete, onArchive } = props;

    const { auth } = useAuth();
    const { setErrorStatus } = useErrorStatus();

    const handleDelete = async () => {
        await queryHelper({
            method: 'post',
            url: '/api/delete-review',
            data: { id: review.id }
        }, setErrorStatus);
        onDelete();
    };

    const handleArchive = async () => {
        await queryHelper({
            method: 'post',
            url: '/api/archive-review',
            data: { id: review.id }
        }, setErrorStatus);
        onArchive();
    };

    if (auth.username != review.author.username && auth.role != 'ADMIN') { return null; }

    return (
        <Menu>
            { auth.role == 'ADMIN' && (
                <MenuItem render={
                    <Button
                        onClick={ onEdit }
                        className="menu__item"
                    >
                        <Icon name= "pencil" />
                        Edit
                    </Button>
                } />
            ) }
            <MenuItem render={
                <Button
                    onClick={ handleArchive }
                    className="menu__item"
                >
                    <Icon name="archive" />
                    { !review.archived ?
                        "Archive" :
                        "Unarchive"
                    }
                </Button>
            } />
            <MenuItem render={
                <Button
                    onClick={ handleDelete }
                    className="menu__item"
                >
                    <Icon name="trash" />
                    Delete
                </Button>
            } />
        </Menu>
    );
};
