// src/components/SearchResults.svelte
<script>
    import Button from '$components/primitives/Button.svelte';
    import RouteIcon from '$components/RouteIcon.svelte';

    import '$assets/styles/components/search-results.scss';

    const { results = [], onOpen } = $props();
</script>

<ul
    id="search-results-container"
    aria-label="Search results"
>
    {#each results as result}
        <li>
                <Button
                    class="search-result"
                    onclick={ () => onOpen(result.id) }
                >
                    { result.name }
                    {#each result.routes as route}
                        <RouteIcon
                            number={ route.number }
                            color={ route.color }
                        />
                    {/each}
                </Button>
            </li>
    {/each}
</ul>

// client/src/components/search-results.jsx
import React from 'react';
import { RouteIcon } from '@components/route-icon';
import { Button } from '@components/button';

import '@assets/styles/components/search-results.scss';

export const SearchResults = props => {
    const { results, openStop } = props;
    
    return results?.map(result => (
        <li key={ result.id }>
            <Button
                className="search-result"
                type="button"
                onClick={ () => openStop(result.id) }
            >
                { result.name }
                { result.routes.map((route, index) => (
                    <RouteIcon
                        key={ index }
                        number={ route.number }
                        color={ route.color }
                    />
                )) }
            </Button>
        </li>
    ));
}
