// src/components/TagSelect.svelte
<script>
    import FormInput from '$components/primitives/FormInput.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import i18n from '$lib/i18n-strings.json';

    import '$assets/styles/components/tag-select.scss';

    const tags = [ 'bench', 'shelter', 'display', 'heating' ];
</script>

<ul class="tag-select">
    {#each tags as tag}
        <li class="tag-select__option">
            <FormInput
                type="checkbox"
                id={ "feature-" + tag }
                name="features"
                value={ tag }
            >
                <Icon name={ tag } />
                { i18n.tagLabels[tag] }
            </FormInput>
        </li>
    {/each}
</ul>

// client/src/components/tag-select.jsx
import React from 'react';
import { FormInput, FormLabel } from '@ariakit/react';
import { Icon } from '@components/icon';
import i18n from '@assets/i18n-strings.json';

import '@assets/styles/components/tag-select.scss';

export const TagSelect = () => {
    return (
        <ul className="tag-select">
            { [ 'bench', 'shelter', 'display', 'heating' ].map(feature => (
                <li className="tag-select__option" key={ feature }>
                    <FormInput
                        type="checkbox"
                        id={ "feature-" + feature }
                        name="features"
                        value={ feature }
                        aria-describedby={ "feature-" + feature + "-label" }
                    />
                    <FormLabel
                        id={ "feature-" + feature + "-label" }
                        htmlFor={ "feature-" + feature }
                    >
                        <Icon name={ feature } />
                        { i18n.tagLabels[feature] }
                    </FormLabel>
                </li>
            )) }
        </ul>
    );
};
