// src/components/TagList.svelte
<script>
    import clsx from 'clsx';
    import AccessibilityState from '$components/AccessibilityState.svelte';
    import Icon from '$components/primitives/Icon.svelte';
    import i18n from "$lib/i18n-strings.json";

    import '$assets/styles/components/tag-list.scss';

    const { state, tags, rounded = false } = $props();
</script>

<ul
    class={ clsx(
        "tag-list", { "tag-list--rounded": rounded }
    ) }
>
    {#if state}
        <li>
            <AccessibilityState
                class="stop-accessibility-state"
                state={ state }
                showHeading="group"
            />
        </li>
    {/if}
    {#each tags as tag}
        <li class="stop-tag">
            <Icon name={ tag } />
            { i18n.tagLabels[tag] }
        </li>
    {/each}
</ul>

// client/src/components/tag-list.jsx
import React from "react";
import { AccessibilityState } from "@components/accessibility-state";
import { Icon } from "@components/icon";
import cx from "classnames";
import i18n from "@assets/i18n-strings.json";

import "@assets/styles/components/tag-list.scss";

export const TagList = props => {
    const { state, tags, className } = props;

    return (
        <ul className={ cx(
            "tag-list",
            className
        ) }>
            { state && (
                <li>
                    <AccessibilityState
                        className="stop-accessibility-state"
                        state={ state }
                        showHeading="group"
                    />
                </li>
            ) }
            { tags?.map(tag => (
                <li className="stop-tag" key={ tag }>
                    <Icon name={ tag } />
                    { i18n.tagLabels[tag] }
                </li>
            )) }
        </ul>
    );
};
