// client/src/components/link.jsx
import React, { forwardRef } from 'react';
import { Link as LinkChild, NavLink as NavLinkChild } from 'react-router-dom';

import '@assets/styles/components/link.scss';

export const Link = forwardRef((props, ref) => {
    const { currentAware = false, ...passthroughProps } = props;
    
    const ChildComponent = currentAware ? NavLinkChild : LinkChild;
    
    return (
        <ChildComponent
            ref={ ref }
            { ...passthroughProps }
        />
    );
});

// src/components/primitives/Link.svelte
<script>
    import { page } from '$app/stores';
    import { emptyMeltElement } from '@melt-ui/svelte';

    import '$assets/styles/components/link.scss';

    const {
        href,
        currentAware = false,
        melt = emptyMeltElement,
        children,
        ...passthroughProps
    } = $props();

    const currentValue =
        currentAware && $page.url.pathname == href ?
        'page' : undefined;
</script>

<a
    { href }
    aria-current={ currentValue }
    use:melt
    { ...passthroughProps }
>
    {@render children()}
</a>
