// client/src/components/menu.jsx
import React from 'react';
import { Menu as MenuParent, MenuButton, useMenuStore } from '@ariakit/react';
import { Icon } from '@components/icon';

import '@assets/styles/components/menu.scss';

export const Menu = props => {
    const { iconName = "ellipsis", toggleAriaLabel = "Toggle options menu", children } = props;
    
    const menuStore = useMenuStore();
    
    return (
        <>
            <MenuButton
                className="menu__toggle button--rounded"
                store={ menuStore }
                { ...toggleAriaLabel && { "aria-label": toggleAriaLabel } }
            >
                <Icon name={ iconName } />
            </MenuButton>
            <MenuParent
                className="menu"
                store={ menuStore }
            >
                { children }
            </MenuParent>
        </>
    );
};

// src/components/primitives/Menu.svelte
<script>
    import { melt, createDropdownMenu } from '@melt-ui/svelte';
    import { setContext } from 'svelte';
    import Button from '$components/primitives/Button.svelte';
    import Icon from '$components/primitives/Icon.svelte';

    import '$assets/styles/components/menu.scss';

    const {
        triggerIcon = "ellipsis",
        'aria-label': ariaLabel = "Toggle options menu",
        children,
        ...passthroughProps
    } = $props();

    const menuStore = createDropdownMenu({
        positioning: {
            placement: 'bottom-end'
        },
        portal: null
    });
    setContext("menu", menuStore);

    const {
        elements: { menu, trigger }
    } = menuStore;
</script>

<Button
    class="menu__toggle button--rounded"
    melt={ trigger }
    aria-label={ ariaLabel }
>
    <Icon name={ triggerIcon } />
</Button>
<div
    class="menu"
    use:melt={ $menu }
    { ...passthroughProps }
>
    {@render children()}
</div>
